/****************************************************************************
**
** Metadata for ACTIVEDSOLib generated by dumpcpp v5.6.3 using
** dumpcpp.exe {450A9894-D9C9-11D1-9966-0000F840FC5E}
** from the type library C:\Program Files (x86)\LeCroy\ActiveDSO\ActiveDSO.ocx
**
****************************************************************************/

#define QAX_DUMPCPP_ACTIVEDSOLIB_NOINLINES
#include "activedsolib.h"

using namespace ACTIVEDSOLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[99];
    char stringdata0[1221];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 25, 0),
QT_MOC_LITERAL(1, 26, 9, 0),
QT_MOC_LITERAL(2, 36, 0, 0),
QT_MOC_LITERAL(3, 37, 4, 0),
QT_MOC_LITERAL(4, 42, 6, 0),
QT_MOC_LITERAL(5, 49, 4, 0),
QT_MOC_LITERAL(6, 54, 4, 0),
QT_MOC_LITERAL(7, 59, 15, 0),
QT_MOC_LITERAL(8, 75, 4, 0),
QT_MOC_LITERAL(9, 80, 6, 0),
QT_MOC_LITERAL(10, 87, 4, 0),
QT_MOC_LITERAL(11, 92, 4, 0),
QT_MOC_LITERAL(12, 97, 8, 0),
QT_MOC_LITERAL(13, 106, 11, 0),
QT_MOC_LITERAL(14, 118, 6, 0),
QT_MOC_LITERAL(15, 125, 10, 0),
QT_MOC_LITERAL(16, 136, 15, 0),
QT_MOC_LITERAL(17, 152, 9, 0),
QT_MOC_LITERAL(18, 162, 9, 0),
QT_MOC_LITERAL(19, 172, 14, 0),
QT_MOC_LITERAL(20, 187, 23, 0),
QT_MOC_LITERAL(21, 211, 11, 0),
QT_MOC_LITERAL(22, 223, 5, 0),
QT_MOC_LITERAL(23, 229, 18, 0),
QT_MOC_LITERAL(24, 248, 17, 0),
QT_MOC_LITERAL(25, 266, 8, 0),
QT_MOC_LITERAL(26, 275, 15, 0),
QT_MOC_LITERAL(27, 291, 9, 0),
QT_MOC_LITERAL(28, 301, 8, 0),
QT_MOC_LITERAL(29, 310, 17, 0),
QT_MOC_LITERAL(30, 328, 11, 0),
QT_MOC_LITERAL(31, 340, 13, 0),
QT_MOC_LITERAL(32, 354, 8, 0),
QT_MOC_LITERAL(33, 363, 13, 0),
QT_MOC_LITERAL(34, 377, 13, 0),
QT_MOC_LITERAL(35, 391, 17, 0),
QT_MOC_LITERAL(36, 409, 26, 0),
QT_MOC_LITERAL(37, 436, 14, 0),
QT_MOC_LITERAL(38, 451, 7, 0),
QT_MOC_LITERAL(39, 459, 10, 0),
QT_MOC_LITERAL(40, 470, 10, 0),
QT_MOC_LITERAL(41, 481, 9, 0),
QT_MOC_LITERAL(42, 491, 12, 0),
QT_MOC_LITERAL(43, 504, 10, 0),
QT_MOC_LITERAL(44, 515, 4, 0),
QT_MOC_LITERAL(45, 520, 9, 0),
QT_MOC_LITERAL(46, 530, 21, 0),
QT_MOC_LITERAL(47, 552, 18, 0),
QT_MOC_LITERAL(48, 571, 12, 0),
QT_MOC_LITERAL(49, 584, 9, 0),
QT_MOC_LITERAL(50, 594, 17, 0),
QT_MOC_LITERAL(51, 612, 14, 0),
QT_MOC_LITERAL(52, 627, 14, 0),
QT_MOC_LITERAL(53, 642, 11, 0),
QT_MOC_LITERAL(54, 654, 12, 0),
QT_MOC_LITERAL(55, 667, 9, 0),
QT_MOC_LITERAL(56, 677, 14, 0),
QT_MOC_LITERAL(57, 692, 11, 0),
QT_MOC_LITERAL(58, 704, 17, 0),
QT_MOC_LITERAL(59, 722, 9, 0),
QT_MOC_LITERAL(60, 732, 14, 0),
QT_MOC_LITERAL(61, 747, 11, 0),
QT_MOC_LITERAL(62, 759, 8, 0),
QT_MOC_LITERAL(63, 768, 6, 0),
QT_MOC_LITERAL(64, 775, 14, 0),
QT_MOC_LITERAL(65, 790, 4, 0),
QT_MOC_LITERAL(66, 795, 13, 0),
QT_MOC_LITERAL(67, 809, 10, 0),
QT_MOC_LITERAL(68, 820, 15, 0),
QT_MOC_LITERAL(69, 836, 12, 0),
QT_MOC_LITERAL(70, 849, 10, 0),
QT_MOC_LITERAL(71, 860, 4, 0),
QT_MOC_LITERAL(72, 865, 21, 0),
QT_MOC_LITERAL(73, 887, 10, 0),
QT_MOC_LITERAL(74, 898, 8, 0),
QT_MOC_LITERAL(75, 907, 13, 0),
QT_MOC_LITERAL(76, 921, 19, 0),
QT_MOC_LITERAL(77, 941, 6, 0),
QT_MOC_LITERAL(78, 948, 9, 0),
QT_MOC_LITERAL(79, 958, 8, 0),
QT_MOC_LITERAL(80, 967, 17, 0),
QT_MOC_LITERAL(81, 985, 12, 0),
QT_MOC_LITERAL(82, 998, 14, 0),
QT_MOC_LITERAL(83, 1013, 13, 0),
QT_MOC_LITERAL(84, 1027, 16, 0),
QT_MOC_LITERAL(85, 1044, 10, 0),
QT_MOC_LITERAL(86, 1055, 10, 0),
QT_MOC_LITERAL(87, 1066, 11, 0),
QT_MOC_LITERAL(88, 1078, 11, 0),
QT_MOC_LITERAL(89, 1090, 7, 0),
QT_MOC_LITERAL(90, 1098, 9, 0),
QT_MOC_LITERAL(91, 1108, 16, 0),
QT_MOC_LITERAL(92, 1125, 7, 0),
QT_MOC_LITERAL(93, 1133, 11, 0),
QT_MOC_LITERAL(94, 1145, 6, 0),
QT_MOC_LITERAL(95, 1152, 7, 0),
QT_MOC_LITERAL(96, 1160, 23, 0),
QT_MOC_LITERAL(97, 1184, 17, 0),
QT_MOC_LITERAL(98, 1202, 17, 0)
    },
    "ACTIVEDSOLib::_DActiveDSO\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0AboutBox\0DeviceClear\0reboot\0Disconnect\0GetByteWaveform\0"
    "traceName\0maxPoints\0whichDataArray\0GetCommaDelimitedString\0inputString\0index\0"
    "GetIntegerWaveform\0GetNativeWaveform\0maxBytes\0transferAsWords\0blockName\0"
    "GetPanel\0GetParameterValue\0sourceTrace\0parameterName\0QString&\0returnedUnits\0"
    "returnedState\0GetScaledWaveform\0GetScaledWaveformWithTimes\0MakeConnection\0"
    "address\0ReadBinary\0ReadString\0maxLength\0RefreshImage\0SerialPoll\0int&\0pollValue\0"
    "SetBinTransferSupport\0BinTransferSupport\0SetBytesRead\0BytesRead\0SetConnectionType\0"
    "ConnectionType\0SetDeviceModel\0DeviceModel\0SetErrorFlag\0ErrorFlag\0SetErrorString\0"
    "ErrorString\0SetNativeWaveform\0srcBuffer\0SetNumChannels\0NumChannels\0SetPanel\0"
    "buffer\0SetRemoteLocal\0mode\0SetScreenType\0ScreenType\0SetSerialNumber\0SerialNumber\0"
    "SetTimeout\0time\0SetupWaveformTransfer\0firstPoint\0sparsing\0segmentNumber\0"
    "StoreHardcopyToFile\0format\0auxFormat\0fileName\0TransferFileToDso\0remoteDevice\0"
    "remoteFileName\0localFileName\0TransferFileToPc\0WaitForOPC\0WaitForSRQ\0timeoutTime\0"
    "WriteBinary\0buf_len\0EOI_state\0WriteGPIBCommand\0cmd_buf\0WriteString\0string\0"
    "control\0ACTIVEDSOLib::ActiveDSO\0Event Interface 1\0_DActiveDSOEvents\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ACTIVEDSOLib___DActiveDSO[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    41, 14, // methods
    10, 398, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 219, 2, 5,
    7, 1, 228, 2, 5,
    9, 3, 231, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 238, 2, 9,
    13, 1, 239, 2, 9,
    15, 0, 242, 2, 9,
    16, 3, 243, 2, 9,
    20, 2, 250, 2, 9,
    23, 3, 255, 2, 9,
    24, 4, 262, 2, 9,
    28, 0, 271, 2, 9,
    29, 4, 272, 2, 9,
    35, 3, 281, 2, 9,
    36, 3, 288, 2, 9,
    37, 1, 295, 2, 9,
    39, 1, 298, 2, 9,
    40, 1, 301, 2, 9,
    42, 0, 304, 2, 9,
    43, 1, 305, 2, 9,
    46, 1, 308, 2, 9,
    48, 1, 311, 2, 9,
    50, 1, 314, 2, 9,
    52, 1, 317, 2, 9,
    54, 1, 320, 2, 9,
    56, 1, 323, 2, 9,
    58, 2, 326, 2, 9,
    60, 1, 331, 2, 9,
    62, 1, 334, 2, 9,
    64, 1, 337, 2, 9,
    66, 1, 340, 2, 9,
    68, 1, 343, 2, 9,
    70, 1, 346, 2, 9,
    72, 3, 349, 2, 9,
    76, 3, 356, 2, 9,
    80, 3, 363, 2, 9,
    84, 3, 370, 2, 9,
    85, 0, 377, 2, 9,
    86, 1, 378, 2, 9,
    88, 3, 381, 2, 9,
    91, 2, 388, 2, 9,
    93, 2, 393, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Bool, QMetaType::Bool, 14,
    QMetaType::Bool,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, 21, 22,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Bool, QMetaType::QString, 17, 25, 26, 27,
    QMetaType::QString,
    QMetaType::Double, QMetaType::QString, QMetaType::QString, 0x80000000 | 32, 0x80000000 | 32, 30, 31, 33, 34,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::Bool, QMetaType::QString, 38,
    QMetaType::QVariant, QMetaType::Int, 25,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Bool,
    QMetaType::Bool, 0x80000000 | 44, 45,
    QMetaType::Void, QMetaType::Bool, 47,
    QMetaType::Void, QMetaType::Int, 49,
    QMetaType::Void, QMetaType::QString, 51,
    QMetaType::Void, QMetaType::QString, 53,
    QMetaType::Void, QMetaType::Bool, 55,
    QMetaType::Void, QMetaType::QString, 57,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 17, 59,
    QMetaType::Void, QMetaType::Int, 61,
    QMetaType::Bool, QMetaType::QString, 63,
    QMetaType::Bool, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::QString, 67,
    QMetaType::Void, QMetaType::QString, 69,
    QMetaType::Bool, QMetaType::Double, 71,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Int, 73, 74, 75,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, 77, 78, 79,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, 81, 82, 83,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, 81, 82, 83,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::Double, 87,
    QMetaType::Bool, QMetaType::QVariant, QMetaType::Int, QMetaType::Bool, 63, 89, 90,
    QMetaType::Bool, QMetaType::QVariant, QMetaType::Int, 92, 89,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, 94, 90,

 // properties: name, type, flags
    47, QMetaType::Bool, 0x01015003, 		 // bool BinTransferSupport
    49, QMetaType::Int, 0x02015003, 		 // int BytesRead
    51, QMetaType::QString, 0x0a015003, 		 // QString ConnectionType
    53, QMetaType::QString, 0x0a015003, 		 // QString DeviceModel
    55, QMetaType::Bool, 0x01015003, 		 // bool ErrorFlag
    57, QMetaType::QString, 0x0a015003, 		 // QString ErrorString
    61, QMetaType::Int, 0x02015003, 		 // int NumChannels
    67, QMetaType::QString, 0x0a015003, 		 // QString ScreenType
    69, QMetaType::QString, 0x0a015003, 		 // QString SerialNumber
    95, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject _DActiveDSO::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ACTIVEDSOLib___DActiveDSO, 0, 0, 0 }
};

void *_DActiveDSO::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ACTIVEDSOLib::_DActiveDSO"))
        return static_cast<void*>(const_cast<_DActiveDSO*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_ACTIVEDSOLib__ActiveDSO[] = {

 // content:
    7, // revision
    96,  // classname
    1, 14, // classinfo
    41, 16, // methods
    9, 400, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    97, 98, 

// signal: name, argc, parameters, tag, flags
    1, 4, 221, 2, 5,
    7, 1, 230, 2, 5,
    9, 3, 233, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 240, 2, 9,
    13, 1, 241, 2, 9,
    15, 0, 244, 2, 9,
    16, 3, 245, 2, 9,
    20, 2, 252, 2, 9,
    23, 3, 257, 2, 9,
    24, 4, 264, 2, 9,
    28, 0, 273, 2, 9,
    29, 4, 274, 2, 9,
    35, 3, 283, 2, 9,
    36, 3, 290, 2, 9,
    37, 1, 297, 2, 9,
    39, 1, 300, 2, 9,
    40, 1, 303, 2, 9,
    42, 0, 306, 2, 9,
    43, 1, 307, 2, 9,
    46, 1, 310, 2, 9,
    48, 1, 313, 2, 9,
    50, 1, 316, 2, 9,
    52, 1, 319, 2, 9,
    54, 1, 322, 2, 9,
    56, 1, 325, 2, 9,
    58, 2, 328, 2, 9,
    60, 1, 333, 2, 9,
    62, 1, 336, 2, 9,
    64, 1, 339, 2, 9,
    66, 1, 342, 2, 9,
    68, 1, 345, 2, 9,
    70, 1, 348, 2, 9,
    72, 3, 351, 2, 9,
    76, 3, 358, 2, 9,
    80, 3, 365, 2, 9,
    84, 3, 372, 2, 9,
    85, 0, 379, 2, 9,
    86, 1, 380, 2, 9,
    88, 3, 383, 2, 9,
    91, 2, 390, 2, 9,
    93, 2, 395, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Bool, QMetaType::Bool, 14,
    QMetaType::Bool,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::QString, QMetaType::QString, QMetaType::Int, 21, 22,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Bool, QMetaType::QString, 17, 25, 26, 27,
    QMetaType::QString,
    QMetaType::Double, QMetaType::QString, QMetaType::QString, 0x80000000 | 32, 0x80000000 | 32, 30, 31, 33, 34,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::QVariant, QMetaType::QString, QMetaType::Int, QMetaType::Int, 17, 18, 19,
    QMetaType::Bool, QMetaType::QString, 38,
    QMetaType::QVariant, QMetaType::Int, 25,
    QMetaType::QString, QMetaType::Int, 41,
    QMetaType::Bool,
    QMetaType::Bool, 0x80000000 | 44, 45,
    QMetaType::Void, QMetaType::Bool, 47,
    QMetaType::Void, QMetaType::Int, 49,
    QMetaType::Void, QMetaType::QString, 51,
    QMetaType::Void, QMetaType::QString, 53,
    QMetaType::Void, QMetaType::Bool, 55,
    QMetaType::Void, QMetaType::QString, 57,
    QMetaType::Bool, QMetaType::QString, QMetaType::QVariant, 17, 59,
    QMetaType::Void, QMetaType::Int, 61,
    QMetaType::Bool, QMetaType::QString, 63,
    QMetaType::Bool, QMetaType::Int, 65,
    QMetaType::Void, QMetaType::QString, 67,
    QMetaType::Void, QMetaType::QString, 69,
    QMetaType::Bool, QMetaType::Double, 71,
    QMetaType::Bool, QMetaType::Int, QMetaType::Int, QMetaType::Int, 73, 74, 75,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, 77, 78, 79,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, 81, 82, 83,
    QMetaType::Bool, QMetaType::QString, QMetaType::QString, QMetaType::QString, 81, 82, 83,
    QMetaType::Bool,
    QMetaType::Bool, QMetaType::Double, 87,
    QMetaType::Bool, QMetaType::QVariant, QMetaType::Int, QMetaType::Bool, 63, 89, 90,
    QMetaType::Bool, QMetaType::QVariant, QMetaType::Int, 92, 89,
    QMetaType::Bool, QMetaType::QString, QMetaType::Bool, 94, 90,

 // properties: name, type, flags
    47, QMetaType::Bool, 0x01015003, 		 // bool BinTransferSupport
    49, QMetaType::Int, 0x02015003, 		 // int BytesRead
    51, QMetaType::QString, 0x0a015003, 		 // QString ConnectionType
    53, QMetaType::QString, 0x0a015003, 		 // QString DeviceModel
    55, QMetaType::Bool, 0x01015003, 		 // bool ErrorFlag
    57, QMetaType::QString, 0x0a015003, 		 // QString ErrorString
    61, QMetaType::Int, 0x02015003, 		 // int NumChannels
    67, QMetaType::QString, 0x0a015003, 		 // QString ScreenType
    69, QMetaType::QString, 0x0a015003, 		 // QString SerialNumber

    0 // eod
};

const QMetaObject ActiveDSO::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ACTIVEDSOLib__ActiveDSO, 0, 0, 0 }
};

void *ActiveDSO::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ACTIVEDSOLib::ActiveDSO"))
        return static_cast<void*>(const_cast<ActiveDSO*>(this));
    return QAxWidget::qt_metacast(_clname);
}

